# Abstract {.unnumbered}

In this study the investigation of multiple machine learning models is conducted on a transporation delay dataset. This dataset is characterized by large outliers and high variatibility within affecting the choice of models suitable for this data. For evaluation regression and classification models that fall under linear models and tree-based models and ensemble methods were used to predict the delay in minutes and the binary classification risk. Assessing these models, performance metrics RMSE, MSE, R², accuracy, precision score alongside other metrics were used to compare performance. The results was that the tree-based models performed greater; specifically the decision tree classifier for predicting delay risk and random forest regressor for predicting delay in minutes. The random forest had a substantially lower error and higher explanation while decision tree for classification achieving the highest accuracy showcasing it's capability to better capture this data's structure. This is suggested by the complexity of the dataset being non-linear, further aligning with tree-based models handling complex data patterns through splitting to effectively reduce variance. Final thoughts, these results showcase the importance of selecting the right models given the context of the problem and the type of data interacted with, proving more effective techniques to solve the problem. 
